In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/KatiaMusun/etl-data-pipeline-2524562022/refs/heads/main/data/raw/A_notas.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df.head()

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025

In [6]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_nota        330 non-null    object
 1   id_estudiante  325 non-null    object
 2   id_curso       328 non-null    object
 3   nota           326 non-null    object
 4   periodo        330 non-null    object
dtypes: object(5)
memory usage: 13.0+ KB

id_nota          0
id_estudiante    5
id_curso         2
nota             4
periodo          0
dtype: int64

Limpiar datos

In [7]:
A_notas = df.copy()

In [8]:
A_notas.columns = A_notas.columns.str.strip().str.lower()

In [9]:
for col in A_notas.select_dtypes(include="object").columns:A_notas[col] = A_notas[col].str.strip()

In [10]:
A_notas = A_notas.replace(r'^\s*$', pd.NA, regex=True)

In [11]:
A_notas = A_notas.drop_duplicates()

In [12]:
A_notas.head()

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025

separar validos de rechazados

In [14]:
validos_notas = A_notas[
    A_notas['id_estudiante'].notna() &
    A_notas['id_curso'].notna() &
    A_notas['nota'].notna()
].copy()

rechazados_notas = A_notas[
    ~(A_notas['id_estudiante'].notna() &
      A_notas['id_curso'].notna() &
      A_notas['nota'].notna())
].copy()

In [15]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_estudiante']):
        motivos.append("id_estudiante_vacio")

    if pd.isna(row['id_curso']):
        motivos.append("id_curso_vacio")

    if pd.isna(row['nota']):
        motivos.append("nota")

    return ",".join(motivos)

rechazados_notas["motivo_rechazo"] = rechazados_notas.apply(motivo, axis=1)

In [16]:
validos_notas.to_csv("A_notas_curated.csv", index=False)
rechazados_notas.to_csv("A_notas_rejects.csv", index=False)

Conectar con postgreSQL(Render)

In [17]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_bv09_user:fCW2NoAjuwpUmvjVY8MbpEYPss9XKGza@dpg-d6qu8cf5gffc73f0e5l0-a.oregon-postgres.render.com/etl_seguros_bv09"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Cargar datos en PostgreSQL

In [18]:
validos_notas.to_sql(
    'A_notas_curated',
    engine,
    if_exists='append',
    index=False
)

303

In [19]:
rechazados_notas.to_sql(
    'A_notas_rejects.csv',
    engine,
    if_exists='append',
    index=False
)

17

Consulta sql

In [21]:
pd.read_sql(
"SELECT * FROM \"A_notas_curated\" LIMIT 10",
engine
)

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025
5   N5005         E1071     C204  3.9  II-2025
6   N5006         E1020     C207  5.2  II-2025
7   N5007         E1102     C200  5.8   I-2025
8   N5008         E1121     C204  2.7   I-2025
9   N5009         E1074     C202  6.2   I-2025